config/routes.rb
Rails.application.routes.draw do
  get 'rows/index'

  get 'accounts/show'
  get 'accounts/edit'
  post 'accounts/edit'

  devise_for :admins
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :events
  resources :tickets
  resources :accounts
  resources :rows, only: [:index]
  root :to => redirect('/events')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :artist, presence: true
  validates :price_low, presence: true
  validates :price_low, presence: true
  validates :price_high, presence: true
  validates :event_date, presence: true
  validate :event_date_not_from_past, :max_not_smaller_than_min

  has_many :tickets
  has_many :rows

  def event_date_not_from_past
    if event_date && event_date < Date.today
      errors.add('Data wydarzenia', 'nie może być z przeszłości')
    end
  end

  def max_not_smaller_than_min
    if price_high && price_low && price_high < price_low
      errors.add('Cena max', 'musi być większa niż min')
    end
  end

  def increased_price
    price_high * 120.0 / 100
  end

  def description_short
    return cut_text description
  end

  def cut_text(tekst)
    if !tekst || tekst.length <= 30
      tekst
    else
      cut(tekst)
    end
  end

  def cut(tekst)
    words = tekst.split(' ')

    length = 0
    final_word = ''
    for i in 0..words.length-1
      if length + 1 + words[i].length + 3 > 25;
        final_word << '...'
        break
      else
        final_word << ' ' + words[i]
        length += words[i].length + 1
      end
    end

    final_word
  end

  def empty
    if !rows || rows.empty?
      return true
    end
    for row in rows
      for seat in row.seats
        if seat.occupied
          return false
        end
      end
    end
    true
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :check_logged_in, only: [:new, :create]
  before_action :set_event, only: [:show, :edit, :update]

  def index
    if user_signed_in? && current_user.admin
      @events = Event.all
    else
      @events = Event.where("event_date < ? and event_date >= ?", Utils.date_in_no_of_days(Date.today, 30), Date.today)
    end
  end

  def new
    @event = Event.new
  end

  def edit
    puts 'to event', @event
  end

  def update
    if @event.update(event_params.except(:rows, :seats_in_row))
      @event.rows = []
      build_seats(params['rows'].to_i, params['seats_in_row'].to_i, @event)
      redirect_to @event, notice: 'Event was successfully updated.'
    end
  end

  def create
    params = event_params
    @event = Event.new(params.except(:rows, :seats_in_row))

    build_seats(params['rows'].to_i, params['seats_in_row'].to_i, @event)

    if @event.save
      flash[:komunikat] = 'Event został poprawnie stworzony.'
      flash[:class] = 'alert alert-success'
      redirect_to "/events/#{@event.id}"
    else
      render 'new'
    end
  end

  def show
    if session[:errors] && !session[:errors].empty? && session[:ticket] && !session[:ticket].empty?
      errors = session[:errors]
      @ticket = Ticket.new(session[:ticket])
      errors.each {|key, value| value.each {|message| @ticket.errors[key] << message}}
      session[:ticket] = nil
      session[:errors] = nil
    else
      @ticket = Ticket.new(event_id: @event.id)
    end
  end

  private
  def build_seats(rows_no, seats_no, event)
    alphabet = ('a'..'z').to_a + ('A'..'Z').to_a
    for i in 0..rows_no - 1
      row = Row.new(row_number: alphabet[i])
      for j in 1..seats_no
        row.seats << Seat.new(occupied: false, seat_number: j)
      end
      event.rows << row
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date, :rows, :seats_in_row, :adults_only)
  end

  def check_logged_in
    authenticate_or_request_with_http_basic ("Ads") do |username, password|
      username == "admin" && password == "admin"
    end
  end

end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_form.html.erb
<%= bootstrap_form_for(event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :artist, id: :event_artist %>
  </div>

  <div class="field">
    <%= form.text_field :description, id: :event_description %>
  </div>

  <div class="field">
    <%= form.text_field :price_low, id: :event_price_low %>
  </div>

  <div class="field">
    <%= form.text_field :price_high, id: :event_price_high %>
  </div>

  <div class="field">
    <%= form.date_field :event_date, id: :event_event_date %>
  </div>

  <% if event.empty%>
    <div class="field">
      <%= form.number_field :rows, id: :rows %>
    </div>

    <div class="field">
      <%= form.label :seats_in_row %>
      <input type="number" id="seats_in_row" name="event[seats_in_row]" class="form-control"/>
    </div>
  <% end %>

  <div class="field">
    <%= form.check_box :adults_only %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_new_ticket.html.erb
<% if user_signed_in? %>

  <%= bootstrap_form_for(ticket) do |form| %>
    <% if ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

        <ul>
          <% ticket.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

<div class="flex-container">    <div class="field">
      <p>
        <strong>Seats:</strong>
        <br>
        <% for row in ticket.event.rows %>
          <span style="font-family: 'Source Code Pro', Monaco, monospace"><%= row.row_number %></span>
          <% for seat in row.seats %>
            <button class="btn btn-primary square" type="button" <%= seat.occupied ? 'disabled' : '' %> value="<%= row.row_number.to_s + seat.seat_number.to_s %>" onclick="yo(this)">
              <%= row.row_number.to_s + seat.seat_number.to_s %>
            </button>
          <% end %>
          <br><br>
        <% end %>
      </p>
    </div></div>

    <div class="field">
      <%= form.text_field :name, id: :ticket_name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.text_area :address, id: :ticket_address, class: 'form-control' %>
    </div>

    <% if ticket.event.event_date.to_date == Date.today %>
      <div class="field">
        <%= form.hidden_field :price, :value => ticket.event.increased_price %>
      </div>
    <% else %>
      <%= form.text_field :price, id: :ticket_price , class: 'form-control'%>
    <% end %>

    <div class="field">
      <%= form.text_field :email_address, id: :ticket_email_address , class: 'form-control'%>
    </div>

    <div class="field">
      <%= form.text_field :phone, id: :ticket_phone, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.hidden_field :event_id, :value => ticket.event_id %>
    </div>

    <div class="field">
      <%= form.hidden_field :seat_id_seq, id: "seat_id_seq" %>
    </div>

    <div class="actions">
      <input type="submit" value="Submit" onclick="setSeatsAsFormParam()" class="btn btn-primary">
    </div>

  <% end %>
<% end %>

app/views/events/_tickets_list.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? && !tickets.empty?%>

  <h1>Tickets</h1>

  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Seats</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% tickets.each do |ticket| %>
      <% if ticket.try(:user) == current_user || current_user.admin %>
        <tr>
          <td><%= ticket.name %></td>
          <td><%= ticket.seat_id_seq %></td>
          <td><%= ticket.address %></td>
          <td><%= ticket.price %></td>
          <td><%= ticket.email_address %></td>
          <td><%= ticket.phone %></td>
          <td><%= link_to 'Show', ticket %></td>
          <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
          <% if current_user.admin %>
            <td><%= link_to 'Destroy', ticket, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
    </tbody>
  </table>

  <br>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div><h2 style="margin-top: 2%">All events</h2>
<br>
  <% (0..@events.count).step(5) do |i| %>
    <% for event in @events[i..i + 4] %>
      <div class="card card-inline" style="width: 19%">
        <div class="card-header">
          <b><%= event.artist %></b> <%= event.event_date < Date.today ? 'Archive' : '' %>
        </div>
        <div class="card-body">
          <%= event.description_short %>
          <br>
          <br>
          <%= event.event_date %>
          <br>
          <br>
          <%= link_to 'See more', "/events/#{event.id}" %>
        </div>
      </div>
    <% end %>
    <br>
    <br>
  <% end %>
  <% if user_signed_in? && current_user.admin %>
    <%= link_to 'Nowe ogłoszenie', new_event_path %>
  <% end %></div>

app/views/events/new.html.erb
<div class="container"><div class="row"><div class="col-8 offset-2">

<h1 style="margin-top: 2%">New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>
</div></div></div>

app/views/events/show.html.erb
<p id="komunikat" class="<%= flash[:class] %>"><%= flash[:komunikat] %></p>

<div class="card">
  <div class="card-body"><p>
    <strong>Name:</strong>
    <%= @event.artist %>
  </p>

    <p>
      <strong>Description:</strong>
      <%= @event.description %>
    </p>

    <% if @event.event_date.to_date == Date.today %>
      <p>
        <strong>Price: </strong>
        <%= @event.increased_price %>
      </p>
    <% else %>
      <p>
        <strong>Price low:</strong>
        <%= @event.price_low %>
      </p>

      <p>
        <strong>Price high:</strong>
        <%= @event.price_high %>
      </p>
    <% end %>

    <p>
      <strong>Event date:</strong>
      <%= @event.event_date %>
    </p>

    <p>
      <strong>Adults only:</strong>
      <%= @event.adults_only %>
    </p>
  </div>
</div>

<div class="flex-container">
  <% if not user_signed_in? %>
    <p>
      <br>
      <% for row in @event.rows %>
        <%= row.row_number %>
        <% for seat in row.seats %>
          <button class="btn btn-primary square" type="button" <%= seat.occupied ? 'disabled' : '' %> value="<%= row.row_number.to_s + seat.seat_number.to_s %>">
            <%= row.row_number.to_s + seat.seat_number.to_s %>
          </button>
        <% end %>
        <br><br>
      <% end %>
    </p>
  <% end %></div>



<%= render "new_ticket", ticket: @ticket %>
<%= render "tickets_list", tickets: Ticket.where('tickets.event_id = ? and tickets.user_id = ?', @event.id, current_user) %>

<% if user_signed_in? && current_user.admin %>
  <%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-link' %>
<% end %>
<%= link_to 'Back', events_path, class: 'btn btn-link' %>