config/routes.rb
Rails.application.routes.draw do
  get 'rows/index'

  get 'accounts/show'
  get 'accounts/edit'
  post 'accounts/edit'

  devise_for :admins
  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :events
  resources :tickets
  resources :accounts
  resources :rows, only: [:index]
  root :to => redirect('/events')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  validates :name, presence: true, length: {minimum: 1}, format: {with: /\p{L}/, message: "can only consist of letters."}
  validates :address, presence: true, length: {minimum: 5}
  validates :email_address, presence: true
  validates :price, presence: true, numericality: true, length: {minimum: 1}
  validates :seat_id_seq, presence: true

  belongs_to :event
  belongs_to :user

  def real_price
    if event
      event.event_date.to_date == Date.today ? event.price_high * 120.0 / 100 : price
    else
      puts "Returning just price in ticket"
      price
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /tickets
  # GET /tickets.json
  def index
    date_from = params['date_from']
    date_to = params['date_to']

    if date_from != nil && date_to != nil && date_from != '' && date_to != ''
      @tickets = Ticket.joins(:event).where("event_date <= ? and event_date >= ?", date_to, date_from)
    elsif date_from != nil && date_from != ''
      @tickets =  Ticket.joins(:event).where("event_date >= ?", date_from)
    elsif date_to != nil && date_to != ''
      @tickets = Ticket.joins(:event).where("event_date <= ?", date_to)
    else
      @tickets = Ticket.all
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    params = ticket_params
    @ticket = Ticket.new(params)
    @ticket.user = current_user

    if age_invalid(current_user)
      redirect_go_back('Event available only for adults.')
      return
    end

    if !@ticket.valid?
      if request.env['HTTP_REFERER'].include? 'events'
        session[:ticket] = @ticket
        session[:errors] = @ticket.errors.messages
        redirect_to request.env['HTTP_REFERER']
        return
      end
      render :new
      return
    end

    no_of_tickets = params['seat_id_seq'].split(',').count

    if no_of_tickets_invalid(no_of_tickets)
      redirect_go_back('Limit of tickets per person is 5.')
      return
    end

    if Date.today != @ticket.event.event_date.to_date
      if amount_invalid(@ticket.price, @ticket.event)
        redirect_go_back('Price needs to be between price low and price high')
        return
      end
    end

    if balance_invalid(current_user, calculate_price_for_purchase(no_of_tickets, @ticket))
      redirect_go_back('Not enough funds.')
      return
    end

    for seat in params['seat_id_seq'].split(', ')
      row = @ticket.event.rows.find_by(row_number: TicketsHelper.get_row_number(seat))
      seat = row.seats.find_by(seat_number: TicketsHelper.get_seat_number(seat))

      if seat == nil
        redirect_go_back('Provided seat number is out of range.')
        return
      end

      if seat.occupied
        redirect_go_back('Chosen seat is already taken.')
        return
      end

      seat.occupied = true
      seat.save
    end

    respond_to do |format|
      if @ticket.save
        take_from_account (calculate_price_for_purchase(no_of_tickets, @ticket)), current_user
        make_seats_occupied(@ticket, ticket_params['seat_id_seq'])

        format.html {redirect_to @ticket, notice: 'Ticket was successfully created.'}
        format.json {render :show, status: :created, location: @ticket}
      else
        format.html {render :new}
        format.json {render json: @ticket.errors, status: :unprocessable_entity}
      end
    end
  end

  def amount_invalid(price, event)
    price > event.price_high || price < event.price_low
  end

  def take_from_account(amount, user)
    user.account.balance -= amount
    user.account.save
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      prev_price = @ticket.price

      new_price = ticket_params['price'].to_f
      if amount_invalid(new_price, @ticket.event)
        redirect_go_back('Price needs to be between price low and price high')
        return
      end

      if balance_invalid(current_user, -(prev_price - new_price))
        redirect_go_back('Not enough funds.')
        return
      end

      old_number_of_tickets = @ticket.seat_id_seq.split(',').count

      if @ticket.update(ticket_params)
        new_number_of_tickets = ticket_params['seat_id_seq'].split(',').count
        difference_in_tickets = new_number_of_tickets - old_number_of_tickets
        current_user.account.balance += ((prev_price - new_price) * new_number_of_tickets) - (difference_in_tickets * new_price)
        current_user.account.save
        format.html {redirect_to @ticket, notice: 'Ticket was successfully updated.'}
        format.json {render :show, status: :ok, location: @ticket}
      else
        format.html {render :edit}
        format.json {render json: @ticket.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    day_diff = Utils.days_til_now(@ticket.event.event_date)
    prev_balance = @ticket.user.account.balance.to_i
    @ticket.user.account.balance += @ticket.price * @ticket.seat_id_seq.split(',').count * (-day_diff / 30.0) * 60.0 / 100
    @ticket.user.account.save
    make_seats_free(@ticket, @ticket.seat_id_seq)
    respond_to do |format|
      format.html {redirect_back fallback_location: '', notice: "Ticket was successfully destroyed. Returned #{@ticket.user.account.balance - prev_balance}"}
      format.json {head :no_content}
    end
  end

  private
  def redirect_go_back(message)
    flash[:komunikat] = message
    flash[:class] = 'alert alert-danger'

    if request.env['HTTP_REFERER'].include? 'events'
      redirect_back fallback_location: ''
    else
      render :new
    end

  end

  def balance_invalid(user, price)
    user.account.balance - price < 0
  end

  def calculate_price_for_purchase(no_of_tickets, ticket)
    ticket.real_price * no_of_tickets
  end

  def no_of_tickets_invalid(no_of_tickets)
    get_total_no_of_tickets(@ticket.event, no_of_tickets) > 5
  end

  def get_total_no_of_tickets(event, no_of_tickets)
    tickets_already_bought = event.tickets.where(user_id: current_user.id)
    no_of_tickets_already_bought = tickets_already_bought
                                       .map {|ticket| TicketsHelper.number_of_seats(ticket)}
                                       .reduce {|first, second| first + second}

    total_no_of_tickets = no_of_tickets + (no_of_tickets_already_bought || 0)
  end

  def age_invalid(user)
    TicketsHelper.age(user.date_of_birth) < 18
  end

  def make_seats_occupied(ticket, seat_id_seq)
    for seat in seat_id_seq.split(', ')
      row = ticket.event.rows.find_by(row_number: TicketsHelper.get_row_number(seat))
      seat = row.seats.find_by(seat_number: TicketsHelper.get_seat_number(seat))
      seat.occupied = true
      seat.save
    end
  end

  def make_seats_free(ticket, id_seat_seq)
    for seat in id_seat_seq.split(', ')
      row = ticket.event.rows.find_by(row_number: TicketsHelper.get_row_number(seat))
      seat = row.seats.find_by(seat_number: TicketsHelper.get_seat_number(seat))
      seat.occupied = false
      seat.save
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
  end

  def correct_user
    if !current_user.admin
      @ticket = current_user.tickets.find_by(id: params[:id])
      redirect_to tickets_path, notice: "Nie jesteś uprawniony do edycji tego biletu" if @ticket.nil?
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
  def TicketsHelper.get_row_number(seat)
    seat[0]
  end

  def TicketsHelper.get_seat_number(seat)
    seat[1..seat.length - 1]
  end

  def TicketsHelper.age(date_of_birth)
    now = Time.now.utc.to_date
    now.year - date_of_birth.year - ((now.month > date_of_birth.month || (now.month == date_of_birth.month && now.day >= date_of_birth.day)) ? 0 : 1)
  end

  def TicketsHelper.number_of_seats(ticket)
    return ticket.seat_id_seq.split(',').count
  end
end

app/views/tickets/_form.html.erb
<%= bootstrap_form_for(ticket) do |form| %>
  <% if ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, id: :ticket_name %>
  </div>

  <div class="field">
    <%= form.text_area :address, id: :ticket_address %>
  </div>

  <div class="field">
    <%= form.text_field :price, id: :ticket_price %>
  </div>

  <div class="field">
    <%= form.text_field :email_address, id: :ticket_email_address %>
  </div>

  <div class="field">
    <%= form.text_field :phone, id: :ticket_phone %>
  </div>

  <div class="field">
    <%= form.text_field :seat_id_seq, id: :ticket_seat_id_seq %>
  </div>


  <% if ticket.new_record? %>
    <div class="field">
      <select class="form-control" name="ticket[event_id]" id="ticket_event_id" onchange="insertPriceLowAndHigh(this)">
        <% for event in Event.all %>
          <option value="<%= event.id %>" data-price-high="<%= event.price_high %>" data-price-low="<%= event.price_low %>"><%= event.artist %></option>
        <% end %>
      </select>
    </div>
  <% else %>
    <div class="field">
      <%= form.hidden_field :event_id, value: ticket.event.id %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<p id="komunikat" class="<%= flash[:class] %>"><%= flash[:komunikat] %></p>
<h1>Editing Ticket</h1>

<%= render 'form', ticket: @ticket %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Tickets</h2>


<div>
  <div class="inline-block"><%= form_tag("/tickets", method: "get", class: 'form-inline') do %>
      <%= label_tag(:date_from, "From date:", class: 'inline margin-right') %>
      <%= date_field_tag(:date_from, {}, class: 'form-control form-control-sm margin-right') %>
      <%= label_tag(:date_to, "To date:", class: 'inline margin-right') %>
      <%= date_field_tag(:date_to, {}, class: 'form-control form-control-sm margin-right') %>
      <%= submit_tag("Search", class: 'inline btn btn-primary btn-sm margin-right') %>
    <% end %>
  </div>
  <%= form_tag("/tickets", method: "get", class: 'inline-block') do %>
    <%= button_to("Show all", {}, class: 'btn btn-primary btn-sm', style: 'margin-bottom: 5%') %>
  <% end %>
</div>
<br>
<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Seats</th>
    <th>Address</th>
    <th>Price</th>
    <th>Email address</th>
    <th>Phone</th>
    <th>Event date</th>
    <th>Artist</th>
    <th colspan="2"></th>
  </tr>
  </thead>

  <tbody>
  <% @tickets.each do |ticket| %>
    <% if user_signed_in? && (ticket.try(:user) == current_user || current_user.admin) %>
      <tr>
        <td><%= ticket.name %></td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= ticket.email_address %></td>
        <td><%= ticket.phone %></td>
        <td><%= ticket.event.event_date %></td>
        <td><%= link_to ticket.event.artist.to_s, event_path(ticket.event) %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <% if current_user.admin %>
          <td><%= link_to 'Destroy', ticket, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 offset-2">
      <h1 class="margin-top">New Ticket</h1>
      <p id="komunikat" class="<%= flash[:class] %>"><%= flash[:komunikat] %></p>

      <%= render 'form', ticket: @ticket %>

      <%= link_to 'Back', tickets_path %>
    </div>
  </div>
</div>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>
<div style="margin-bottom: 40px;">
<p>
  <strong>Name:</strong>
  <%= @ticket.name %>
</p>

<p>
  <strong>Seats:</strong>
  <%= @ticket.seat_id_seq %>
</p>

<p>
  <strong>Address:</strong>
  <%= @ticket.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket.price %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @ticket.email_address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @ticket.phone %>
</p>

<p>
  <strong>Event:</strong>
  <%= @ticket.event.try(:artist) %>
</p></div>

<%= link_to 'Edit', edit_ticket_path(@ticket)%>
<%= link_to 'Back', tickets_path %>